**

!*.py
!LICENSE
!README.md

!conf/
!conf/**
!datasets/
!datasets/**
!distributed_fn/
!distributed_fn/**
!env/
!env/**
!metrics/
!metrics/**
!models/
!models/**
!planning/
!planning/**

!infra/
!infra/container/
!infra/container/**
!infra/experiments/
!infra/experiments/**

**/__pycache__/
**/*.pyc
env/deformable_env/src/sim/assets/
models/encoder/r3m/
